### PR TITLE
build(deps): bump regex-syntax from 0.6 to 0.7

### PR DESCRIPTION
**Pull request by sjackman**
- Bump `regex-syntax` from 0.6 to 0.7
- Update `proptest/src/string.rs` for `regex-syntax` 0.7

### CODE REVIEW

**Comment by tzemanovic** [comment]
There are some breaking changes in regex-syntax affecting proptest/src/string.rs. We could probably support both versions by using `cfg_accessible`

**Comment by sjackman** [comment]
@tzemanovic I've updated `proptest/src/string.rs` for `regex-syntax` 0.7.

**Review by tzemanovic — APPROVED** [review]
thanks!

**Comment by sjackman** [comment]
@tzemanovic Is this PR good to merge, or do you need anything else from me? I'd love to see a stable release on crates once it's merged!

**Comment by sjackman** [comment]
Thank you very much for merging my PR, @tzemanovic and @matthew-russo! I look forward to a release on crates.io that includes this change.

**Comment by sjackman** [comment]
@tzemanovic Any plans for an upcoming release with this change?

**Comment by matthew-russo** [comment]
@sjackman Im planning a release either tonight or tomorrow.

**Comment by sjackman** [comment]
Woohoo! Thank you, Matthew!

**Comment by matthew-russo** [comment]
v1.3.0 is published on crates now

**Comment by sjackman** [comment]
👏 Thank you, Matthew! 😁

**Pull request merged**
