### PR TITLE
Fix WebAssembly support

### LINKED ISSUE #137: Support building on webassembly
It would be great if proptest could be built on WASM. Slightly related to #47 but more specific, since proptest can almost be compiled to webassembly already.

I'm already disabling [the default forking feature](https://altsysrq.github.io/proptest-book/proptest/forking.html), to avoid the `rusty-fork` dependency.

The only thing blocking building proptest on webassembly is [these few lines](https://github.com/AltSysrq/proptest/blob/d1c4b049337d2f75dd6f49a095115f7c532e5129/proptest/src/arbitrary/_std/env.rs#L89), importing `std::os::unix` inside a `#[cfg(not(target_os = "windows"))]` block.

Could the `osstring_invalid_string` function be constrained more, by excluding `wasm32` for example? Or maybe there's a better solution to avoid using `std::os::unix` on all non-windows targets?

### PR DESCRIPTION
**Pull request by RReverser**
Hides a few paths, that fail at runtime on wasm32-unknown-unknown, under conditional compilation.

Fixes #137.

### CODE REVIEW

**Comment by RReverser** [comment]
@matthew-russo Why was this closed?

**Comment by RReverser** [comment]
Oh no, looks like you deleted the master branch instead of renaming in Github settings? That does automatically close all the associated PRs :(

**Comment by matthew-russo** [comment]
fun

**Comment by matthew-russo** [comment]
let me see if i can undo

**Comment by RReverser** [comment]
From personal past experience, I don't think you can. But let me know if you want to cherry-pick this manually or for me to reopen the PR.

**Comment by matthew-russo** [comment]
I'll deal with it -- sorry about the hassle. On the bright side it'll force me to look at all the PRs that had been open without getting attention.

**Comment by matthew-russo** [comment]
this was rebased here:
https://github.com/proptest-rs/proptest/pull/458

which is now replaced targeting the new branch:
https://github.com/proptest-rs/proptest/pull/519

**Pull request closed without merging**
