### PR TITLE
`Arbitrary` impls for `NonZero*` types

### PR DESCRIPTION
**Pull request by cameron1024**
Adds `Arbitrary` impl for all the `core::num::NonZero*` types

### CODE REVIEW

**Review by matthew-russo — DISMISSED** [review]

**Review by matthew-russo — CHANGES_REQUESTED** [review]
Can we add an entry to CHANGELOG.md (https://github.com/proptest-rs/proptest/blob/master/CONTRIBUTING.md#updating-the-changelog) under the `New Additions` section?

**Comment by cameron1024** [comment]
Not sure if `1.1.0` makes more sense than `1.0.1`, happy with either :shrug:

**Comment by matthew-russo** [comment]
I think we should just label it as "Unreleased Changes" and once we are ready to make a release we can figure the proper semver

**Review by matthew-russo — APPROVED** [review]

**Comment by matthew-russo** [comment]
@rex-remind101 @russelldb Can you give this a look when you get a chance

**Review by russelldb — APPROVED** [review]
LGTM

**Review by rex-remind101 — APPROVED** [review]
great 👍

**Pull request merged**
